services:
  app:
    image: python:3-slim
    command: python /app/app.py
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:9008:8080"
    init: true
    tty: true
    mem_limit: 100m
    cpus: 0.1
