services:
  esphome:
    image: ghcr.io/esphome/esphome
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    tty: true
    init: true
#    privileged: true
    network_mode: host # exposes :6052
    env_file:
      - esphome.env
