---
- name: Setup root crontab
  hosts: home
  become: true
  gather_facts: false
  tasks:
    - name: Cron - Restic backup
      ansible.builtin.cron:
        name: restic backup
        minute: 0
        job: "{{ deploy_dir }}/bin/healthcheck restic-backup {{ deploy_dir }}/bin/restic-backup"
    - name: Cron - Restic prune
      ansible.builtin.cron:
        name: restic prune
        minute: 30
        hour: "*/3"
        job: "{{ deploy_dir }}/bin/healthcheck restic-prune {{ deploy_dir }}/bin/restic-prune"
    - name: Cron - SMART short
      ansible.builtin.cron:
        name: SMART short
        special_time: weekly
        job: "{{ deploy_dir }}/bin/smartshort"
    - name: Cron - SMART long
      ansible.builtin.cron:
        name: SMART long
        special_time: monthly
        job: "{{ deploy_dir }}/bin/smartlong"
