---
- name: Setup root crontab
  hosts: vps
  become: true
  gather_facts: false
  tasks:
    - name: Install restic
      ansible.builtin.apt:
        pkg:
          - restic
    - name: Cron - Restic backup
      ansible.builtin.cron:
        name: restic backup
        minute: 0
        job: "{{ deploy_dir }}/bin/healthcheck restic-backup {{ deploy_dir }}/bin/restic-backup"
    - name: Cron - Restic prune
      ansible.builtin.cron:
        name: restic prune
        minute: 30
        hour: "*/3"
        job: "{{ deploy_dir }}/bin/healthcheck restic-prune {{ deploy_dir }}/bin/restic-prune"
