---
- name: Firewall config Home
  hosts: home
  gather_facts: false
  become: true
  tasks:
    - name: Install ufw
      become: true
      ansible.builtin.apt:
        pkg:
          - ufw
    - name: Allow http
      community.general.ufw:
        rule: allow
        port: http
    - name: Allow https
      community.general.ufw:
        rule: allow
        port: https
    - name: Allow in tailscale0
      community.general.ufw:
        rule: allow
        direction: in
        interface: tailscale0
    - name: Allow FTP in home network
      community.general.ufw:
        rule: allow
        from_ip: 192.168.0.0/24
        proto: tcp
        port: "7020:7021"
    - name: Allow UPS mon
      community.general.ufw:
        rule: allow
        from_ip: 192.168.0.0/24
        port: "3493"
    - name: Allow syncthing
      community.general.ufw:
        rule: allow
        port: "21027"
    - name: Allow Samba
      community.general.ufw:
        rule: allow
        from_ip: 192.168.0.0/24
        name: "Samba"
    - name: Enable UFW with deny default
      community.general.ufw:
        state: enabled
        default: deny
