---
- name: Update system
  hosts: common
  gather_facts: false
  become: true
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400
