services:
  code:
    image: ghcr.io/linuxserver/code-server
    env_file: code.env
    restart: always
    volumes:
      - ./code_data:/config
    ports:
      - "127.0.0.1:9002:8443"
    mem_limit: 512m
    cpus: 0.5
