services:
  piper:
    image: rhasspy/wyoming-piper
    restart: always
    ports:
      - '10200:10200'
    volumes:
      - './piper-data:/data'
    command: --voice fr-siwis-medium
    cpus: 1
    mem_limit: 500m

  whisper:
    image: rhasspy/wyoming-whisper
    restart: always
    ports:
      - '10300:10300'
    volumes:
      - './whisper-data:/data'
    command: --model small --language fr --beam-size 10
    cpus: 6
    mem_limit: 8g
