---
- name: Setup rclone mounts
  hosts: vps
  tasks:
    - name: Create target mount dir
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/mount/ovh-immich"
        state: directory
        mode: "0755"
    - name: Write rclone mount service
      become: true
      ansible.builtin.template:
        src: "templates/rclone/rclone@.service.j2"
        dest: "/etc/systemd/system/rclone@.service"
        mode: "0644"
      notify:
        - Restart rclone mounts

  handlers:
    - name: Restart rclone mounts
      become: true
      ansible.builtin.systemd:
        name: rclone@ovh-immich
        state: restarted
        daemon_reload: true
