---
- name: Simple packages
  hosts: common
  become: true
  tasks:
    - name: Install tools
      ansible.builtin.apt:
        pkg:
          - fish
          - unzip
          - zip
          - mysql-client # required for mysqldump
