---
- name: Install Syncthing
  hosts: common
  become: true
  tasks:
    - name: Download Syncthing GPG Key
      ansible.builtin.get_url:
        url: https://syncthing.net/release-key.gpg
        dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg
        mode: "0644"
    - name: Add Syncthing repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
        state: present
        filename: syncthing
    - name: Install Syncthing
      ansible.builtin.apt:
        name: syncthing
        update_cache: true
        state: present
