---
- name: Install Tailscale
  hosts: common
  become: true
  tasks:
    - name: Download Tailscale GPG Key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: "0644"
    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: "0644"
    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        update_cache: true
        state: present
