---
- name: Reload daemon
  ansible.builtin.service:
    daemon_reload: true
  become: true
- name: Restart service {{ ghost_site }}
  ansible.builtin.command:
    cmd: ghost restart
    chdir: "{{ deploy_dir }}/{{ ghost_site }}"
  changed_when: true
