---
- name: Display
  hosts: servers
  gather_facts: false
  tasks:
    - name: Fix git config
      community.general.git_config:
        scope: global
        name: merge.conflictstyle
        value: diff3
    - name: Pull git repo
      ansible.builtin.git:
        executable: /usr/bin/git
        repo: https://git.augendre.info/gaugendre/display.git
        dest: "{{ dir }}/sources"
        version: HEAD # noqa: latest[git] # we want the latest revision
    - name: Docker
      ansible.builtin.include_role:
        name: docker

  vars:
    docker_app_name: display
    docker_build: always
    dir: /mnt/data/{{ docker_app_name }}
