---
- name: Nextcloud2
  hosts: servers
  gather_facts: false
  tasks:
    - name: Docker
      ansible.builtin.include_role:
        name: docker
    - name: Install rclone
      become: true
      ansible.builtin.apt:
        name:
          - rclone
    - name: Copy config file
      become: true
      ansible.builtin.copy:
        src: files/nextcloud-aio-rclone.conf
        dest: /root/.config/rclone/rclone.conf
        mode: "0600"

  vars:
    docker_app_name: nextcloud-aio
