---
servers:
  hosts:
    ubuntu:
      ansible_host: 192.168.0.6
      ansible_user: gaugendre
      ansible_python_interpreter: auto_silent
      deploy_dir: /mnt/data
vps:
  hosts:
    vps-1:
      ansible_host: vps-1
      ansible_user: ubuntu
      ansible_python_interpreter: auto_silent
      deploy_dir: /home/ubuntu/deploy
common:
  hosts:
    ubuntu:
      ansible_host: 192.168.0.6
      ansible_user: gaugendre
      ansible_python_interpreter: auto_silent
      deploy_dir: /mnt/data
    vps-1:
      ansible_host: vps-1
      ansible_user: ubuntu
      ansible_python_interpreter: auto_silent
      deploy_dir: /home/ubuntu/deploy
