---
servers:
  hosts:
    ubuntu:
      ansible_host: 192.168.0.6
      ansible_user: gaugendre
      ansible_python_interpreter: auto_silent
#    vps-1:
#      ansible_host: 146.59.145.216
#      ansible_user: ubuntu
#      ansible_python_interpreter: auto_silent
