services:
  wallabag:
    image: wallabag/wallabag:latest
    env_file: wallabag.env
    restart: always
    volumes:
      - ./wallabag_data/data:/var/www/wallabag/data
      - ./wallabag_data/images:/var/www/wallabag/web/assets/images
    ports:
      - "127.0.0.1:8009:80"
    cpus: 0.5
    mem_limit: 256m
    # Migrate DB if needed after update
    labels:
      com.centurylinklabs.watchtower.lifecycle.post-update: "/var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction"
      com.centurylinklabs.watchtower.lifecycle.post-update-timeout: "600"
