services:
  wallabag:
    image: wallabag/wallabag:latest
    env_file: wallabag.env
    restart: always
    volumes:
      - ./wallabag_data/data:/var/www/wallabag/data
      - ./wallabag_data/images:/var/www/wallabag/web/assets/images
    ports:
      - "8009:80"
